version: '3'
services:

  travelperk-python-api-types:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travelperk-python-api-types
    entrypoint: "pipenv run pytest"
    tty: false
    working_dir: /app
    volumes:
      - ./:/app
